      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "Resume - Comic/package-lock.json"


      - name: Install
        run: npm ci
        working-directory: "Resume - Comic"

      - name: Build
        run: npm run build
        working-directory: "Resume - Comic"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "Resume - Comic/dist"
